### PR TITLE
chore(deps): Allow Sinon v4 peer dependency

### PR DESCRIPTION
**Pull request by merlinc**

### CODE REVIEW

**Comment by isuda** [comment]
It would be great if this could be merged soon!

**Comment by AlexEvanczuk** [comment]
@kmees Is this good to merge?  Would love to incorporate this into our project so we can bump sinon.

**Comment by AlexEvanczuk** [comment]
Oh by the way if it helps, locally I bumped the version (same as this PR), and ran our company's test suite and everything passed.

**Comment by Kyoss79** [comment]
Please merge this soon. It's really needed.

**Comment by dpogue** [comment]
@bankyadam @kmees I've also tested and confirmed this works

**Comment by HughePaul** [comment]
:+1:  LGTM

**Comment by bankyadam** [comment]
1.3.3 released

**Pull request merged**
