### PR TITLE
Avoid resolving package.json

### PR DESCRIPTION
**Pull request by ntkme**
This PR fixes the following error when resolving `package.json` with recent node versions (see https://github.com/nodejs/node/issues/33460 for background):

```
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /build/node_modules/sinon/package.json
```

### CODE REVIEW

**Comment by mwilc0x** [comment]
ping +1

**Comment by klievanskyi** [comment]
One more ping +1

**Comment by jquense** [comment]
pleeease

**Comment by ntkme** [comment]
Chai.js >= 4.3.6 and Sinon.js >=13.0.0 should have fixed this error. Closing.

**Pull request closed without merging**
