### PR TITLE
Lolex dep

### PR DESCRIPTION
**Pull request by joscha**
Sinon 1.17 does not bring Lolex out of the box any more.

Depends on #29.

### CODE REVIEW

**Comment by tregusti** [comment]
@kmees Any issues with the currently open pull requests? Can you please merge oterwise? They have been open for quite some time now.

Thank you!

**Comment by bricss** [comment]
It's all about that issue https://github.com/kmees/karma-sinon-chai/issues/26 plz merge it.

**Comment by joscha** [comment]
@kmees anything I can do to help get this released?

**Comment by joscha** [comment]
Thank you!

**Pull request merged**
