### PR TITLE
chore(deps): bump dependencies to latest versions

### PR DESCRIPTION
**Pull request by bricss**
Bumped dependencies. At least it will make it possible to use sinon ^2.0.0 with sinon-chai ^2.9.0. 🛠

### CODE REVIEW

**Comment by semurgx** [comment]
Is this going to be merged?

**Comment by bricss** [comment]
Hope that one day in another universe someone brave enough will press the merge button ✊

**Comment by jeremyzahner** [comment]
@kmees Ping

**Comment by bricss** [comment]
@adambrunner Ping

**Comment by semurgx** [comment]
@adambrunner How about publishing it in npm?

**Comment by bricss** [comment]
@adambrunner Could you please, bump plugin version and publish it to npm?

**Comment by jeremyzahner** [comment]
@adambrunner Or invite a collaborator who can do it. =)

**Pull request merged**
